package code.enumeration;

public enum ExitKey {

    EXIT_CARNIVAL,
    EXIT_COPPER_HUB,
    EXIT_GOLD_HUB,
    EXIT_PLATINUM_HUB,
    EXIT_KEY_SHOP,
    EXIT_FOOD_SHOP,
    EXIT_FIND_NUMBER,
    EXIT_HANGMAN,
    EXIT_HANOI_TOWER,
    EXIT_KARAOKE,
    EXIT_QTE,
    EXIT_QUESTIONS,
    EXIT_RIDDLE,
    EXIT_ROCK_PAPER_SCISSORS,
    EXIT_TIC_TAC_TOE

}
