package code.enumeration;

public enum NpcKey {

    GESUI_HUN_VON_DEUR,
    GESUI_HUN_GUYDE,
    PIERRE_DUPUIS,
    KHARRA_OKEY,
    SAGRAT_OPUBICE,
    JEAN_PIERRE_FOUGAS,
    VINCENT_FAYGAF,
    SAMUEL_OUTIENNE,
    MARINA_LEPENDU,
    GEOFFREY_KOFRED,
    DONTE_TOUCHME

}
